spring:
  application:
    name: '@project.name@'
    description: '@project.description@'

  redis:
    host: localhost
    port: 6379

  kafka:
    bootstrap-servers: localhost:29092
    client-id: seller-service
    producer:
      enabled: true
      retries: 1

server:
  servlet:
    context-path: /
  port: 8080